services:
  tcp: &vpn
    image: ${IMAGE:-janole/vpn}
    volumes:
      - ./conf/openvpn:/conf/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - ${VPNPORT:-1194}:${VPNPORT:-1194}/tcp
    depends_on:
      - config

  udp:
    <<: *vpn
    ports:
      - ${VPNPORT:-1194}:${VPNPORT:-1194}/udp
    environment:
      - SERVERCONF=/conf/openvpn/udp-server.conf

  config:
    image: ${IMAGE:-janole/vpn}
    build:
      tags:
        - ${IMAGE:-janole/vpn}:latest
        - ${IMAGE:-janole/vpn}:${VERSION:-dev}
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    env_file:
      - .env
    volumes:
      - ./conf:/conf
    command: "/init-vpn.sh"
