name: Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '16 23 * * *'

permissions:
  actions: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Pull Image
        run: docker pull "${{ vars.IMAGE }}:latest"

      - name: Run trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: "${{ vars.IMAGE }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          scanners: "vuln"
          severity: "LOW,MEDIUM,HIGH,CRITICAL"
          version: "v0.71.2"
        env:
          TRIVY_DB_REPOSITORY: aquasec/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: aquasec/trivy-java-db:1

      - name: Try to start build workflow if trivy failed
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl --fail-with-body -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"ref":"main"}' \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/ci.yml/dispatches"
