name: trivy

on:
  workflow_dispatch:
  schedule:
    - cron: '16 23 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Pull Image
        run: docker pull ${{ vars.IMAGE }}

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ vars.IMAGE }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"

      - name: Try to start build workflow if trivy failed
        if: ${{ failure() }}
        run: |
          curl -X POST -u ${{ secrets.PAT }} -H "Accept: application/vnd.github.v3+json" -d '{"ref":"refs/heads/master"}' https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/ci.yml/dispatches
